name: Generate Changelog on Release Branch

permissions:
  contents: write

on:
  push:
    branches:
      - 'release/*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gerar o arquivo CHANGELOG.md
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GT_TOKEN }}
          output-file: "CHANGELOG.md"
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
